[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["Itsusinn奕䜣 <itsusinn@foxmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"

#[features]
#derive = true
[lib]
proc-macro = true

