name: build

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Resume cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          /tmp/assimp
        key: ${{ runner.os }}-itsusinn-another-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-itsusinn-another
    - name: Install assimp
      run: |
        sudo apt-get install libassimp-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Install stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Resume cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          /tmp/assimp
        key: ${{ runner.os }}-itsusinn-another-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-itsusinn-another-
    - name: Install assimp
      run: brew install assimp
    - name: Install stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
