name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Resume cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          /tmp/assimp
        key: ${{ runner.os }}-itsusinn-another-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-itsusinn-another-
    - name: Install assimp
      run: sudo bash ${GITHUB_WORKSPACE}/install_assimp.bash
    - name: Install stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
